# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170819_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-event', 'time']},
        ),
    ]
