# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170819_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date', 'start_time', '-last_edited']},
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
